trigger:
  branches:
    include:
      - main

jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy to AKS'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: |
      # Clone the Git repository
      git clone $(Build.Repository.Uri)
      cd <repository-folder>

      # Build your application (modify as per your build process)
      # Example: For a .NET application
      dotnet restore
      dotnet build --configuration Release

    displayName: 'Build the application'

  - task: Kubernetes@1
    displayName: 'Deploy to AKS'
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscriptionEndpoint: '<azure-service-connection>'
      azureResourceGroup: '<resource-group-name>'
      kubernetesCluster: '<aks-cluster-name>'
      command: 'apply'
      arguments: '-f <path-to-kubernetes-yaml-file>'
      secretType: 'kubectl'
      secretArguments: '-o yaml'
