apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
      deployment: blue
  template:
    metadata:
      labels:
        app: my-app
        deployment: blue
    spec:
      containers:
        - name: main
          image: my-app:blue
          ports:
            - containerPort: 8080
          # Add other container configuration settings as needed
---
apiVersion: networking.k8s.io/v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
    deployment: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-green
spec:
  replicas: 0
  selector:
    matchLabels:
      app: my-app
      deployment: green
  template:
    metadata:
      labels:
        app: my-app
        deployment: green
    spec:
      containers:
        - name: main
          image: my-app:green
          ports:
            - containerPort: 8080
          # Add other container configuration settings as needed
---
apiVersion: networking.k8s.io/v1
kind: Service
metadata:
  name: my-app-service-green
spec:
  selector:
    app: my-app
    deployment: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
